apiVersion: apps/v1
kind: Deployment
metadata:
  name: investor-frontend
  namespace: investort-portal-new
  labels:
    app: investor-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: investor-frontend
  template:
    metadata:
      labels:
        app: investor-frontend
    spec:
      containers:
        - name: frowned deployment
          image: 844811022199.dkr.ecr.eu-central-1.amazonaws.com/investor-portal-frontend:ace-003
          ports:
            - name: http
              containerPort: 80
