apiVersion: v1
kind: Service
metadata:
  name: investor-frontend
  namespace: investor-portal-new
  labels:
    app: nodejs
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: investor-frontend
