apiVersion: apps/v1
kind: Deployment
metadata:
  name: investorfrontend
  labels:
    app: investor-portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: investor-portal
  template:
    metadata:
      labels:
        app: investor-portal
    spec:
      containers:
      - name: investorfrontend
        image: 844811022199.dkr.ecr.eu-central-1.amazonaws.com/investor-portal-frontend:ace-003
        imagePullPolicy: Always
        ports:
        - containerPort: 80
